---
title: Liuyang's Blog
timezone: Asia/Singapore
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
include:
- _pages
email: t@sfdye.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: https://sfdye.com
twitter_username: sfdye
github_username: sfdye
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default
permalink: "/:year/:month//:title"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-archives
name: Wan Liuyang
author:
  name: Wan Liuyang
  location: Singapore
  avatar: "/assets/images/avatar.jpg"
  bio: Latte-driven, Python & Django Developer
  email: t@sfdye.com
  github: sfdye
  twitter: sfdye
  weibo: 5042410848
twitter:
  username: sfdye
facebook:
  username: liuyang.wan
analytics:
  provider: google-universal
  google:
    tracking_id: UA-107754442-1
comments:
  provider: disqus
  disqus:
    shortname: sfdye
paginate: 5
words_per_minute: 150
og_image: /assets/images/fish.jpg
category_archive:
  type: jekyll-archives
  path: "/categories/"
tag_archive:
  type: jekyll-archives
  path: "/tags/"
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
